apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio-azure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/Nagham94/DevOps-MultiCloud-Project
    targetRevision: main
    path: kubernetes/overlays/azure

  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        maxDuration: 3m
        factor: 2