[jenkins]
# to ssh into the jenkins vm using tunnel, we will use the localhost IP and specify the port that we will forward to the jenkins vm
jenkins-vm ansible_host=127.0.0.1

[jenkins:vars]
ansible_user=azureuser
ansible_port=2222
ansible_ssh_private_key_file=ansible/jenkins_vm.pem
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'