apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: 254652353999.dkr.ecr.eu-north-1.amazonaws.com/portfolio-website
    newName: acrprodNagham.azurecr.io/portfolio-website
    newTag: "latest"