apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Override image to use ECR
# Jenkins pipeline updates the tag here on every build
images:
  - name: 254652353999.dkr.ecr.eu-north-1.amazonaws.com/portfolio-website
    newName: 254652353999.dkr.ecr.eu-north-1.amazonaws.com/portfolio-website
    newTag: "latest"